# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20170122_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
